### ISSUE TITLE
Edit Dependency - Not possible to edit dependency

### ISSUE THREAD

**Issue by shaberberg** [SlipperyPenguine/tracker#6]
Reproduction:
1) Create a dependency and leave "Internal Dependency Blank"
2) Fill out all required fields
3) Re-open dependency and try to edit Dependency -> Not possible (maybe by design)

I also found no way of deleting the dependency

**Comment by SlipperyPenguine** [comment]
well this turned out to be a bit more of an epic change than expected.  Bug is fixed and a few enhancements done along the way.

You can now delete dependencies

Forms show validation much more clearly
